version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
farmersdelight = true
everycomp = true
mcwfences = true
tconstruct = true
quad-lolmsmv = true
mcwbyg = true
infinitybuttons = true
doapi = true
brewery = true
festive_delight = true
mcwstairs = true
star = true
lolmfv = true
friendsandfoes = true
natures_spirit = true
copycats = true
stonezone = true
furniture = true
comforts = true
yigd = true
woodwevegot = true
mcwbridges = true
quad-lolmbhv = true
railways = true
bloomingnature = true
handcrafted = true
thaumon = true
herbalbrews = true
vegandelight = true
exposure = true
endersdelight = true
supplementaries = true
valhelsia_furniture = true
culturaldelights = true
create = true
cornexpansion = true
windchimes = true
frightsdelight = true
estrogen = true
lolmcbv = true
betterenddelight = true
biomeswevegone = true
minecraft = true
rusticdelight = true
natures_delight = true
mcwfurnitures = true
sophisticatedstorage = true
dumplings_delight = true
doggomodoverhauled = true
sliceanddice = true
creeperoverhaul = true
lolmgv = true
tradingpost = true
expandeddelight = true
fancydelight = true
bushierflowers = true
candlelight = true
createfood = true
mcwroofs = true
mcwwindows = true
storagedelight = true
oceansdelight = true
betterend = true
another_furniture = true
lolmbv = true
diagonalwalls = true
chalk = true
quad-lolmjnv = true
mcwpaths = true
nethersdelight = true
create_enchantment_industry = true
mcwtrpdoors = true
fastpaintings = true
mcwlights = true
bellsandwhistles = true
botanypots = true
milk = true
amendments = true
diagonalfences = true
lolmcv = true
bakery = true
extendedgears = true
sophisticatedbackpacks = true
treechop = true
lilis_lucky_lures = true
mcwdoors = true
cratedelight = true
ubesdelight = true
lolmlv = true
garnished = true
suppsquared = true
sawmill = true
convenientdecor = true
farm_and_charm = true
interiors = true
luphieclutteredmod = true
wildernature = true
lolmlmv = true
createdeco = true
nethervinery = true
lolmcmv = true
beautify = true
immersive_weathering = true
decorative_blocks = true
diagonalwindows = true
doaddonfluids = true
crittersandcompanions = true
lolmblv = true
vinery = true
meadow = true
grapplemod = true
hearth_and_home = true
